/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import info.*;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;


/**
 *
 * @author kevin
 */
public class UI extends javax.swing.JFrame {

    private List<Animal> animales;
    private BackgroundPanel mainPanel;
    private int nivel;

    /**
     * Creates new form UI
     */
    public UI() {

        animales = new ArrayList<>();
        nivel = 1;
        cargarAnimales();
        initComponents();
        misComponents();
    }

    private void cargarAnimales() {

        Properties information = new Properties();

        try (InputStream input = getClass().getResourceAsStream("/info/information")) {
            if (input == null) {
                throw new IOException("Properties file not found");
            }
            information.load(input);
        } catch (IOException ex) {
            ex.printStackTrace();
        }

        animales.add(new Tipo.Felivoltio("Meu", "Felivoltio", "Electrico", 100, 1, "T:\\TAI\\DEVELOPER\\DAW\\M3\\UF5\\Generics\\Tamagochi\\prueba poo\\src\\main\\meu.jpg", information.getProperty("Meu"), 50, 50));
        animales.add(new Grupo.Gusano("Max", "Gusano", "Reptiles", 100, 2, "T:\\TAI\\DEVELOPER\\DAW\\M3\\UF5\\Generics\\Tamagochi\\prueba poo\\src\\main\\p.png",information.getProperty("Meu"), 50, 50));
        animales.add(new Tipo.Aguila("Articuno", "Aguila", "Aves", 100, 3, "T:\\TAI\\DEVELOPER\\DAW\\M3\\UF5\\Generics\\Tamagochi\\prueba poo\\src\\main\\p.png",information.getProperty("Meu"), 50, 50));
        animales.add(new Tipo.Tiburon("Laboon", "Tiburon", "Peces", 100, 4, "T:\\TAI\\DEVELOPER\\DAW\\M3\\UF5\\Generics\\Tamagochi\\prueba poo\\src\\main\\p.png",information.getProperty("Meu"), 50, 50));
        animales.add(new Tipo.Lagarto("Zeira", "Lagarto", "Reptiles", 100, 5, "T:\\TAI\\DEVELOPER\\DAW\\M3\\UF5\\Generics\\Tamagochi\\prueba poo\\src\\main\\p.png",information.getProperty("Meu"), 50, 50));
        animales.add(new Tipo.Koala("Benito", "Koala", "Mamiferos", 100, 6, "T:\\TAI\\DEVELOPER\\DAW\\M3\\UF5\\Generics\\Tamagochi\\prueba poo\\src\\main\\p.png",information.getProperty("Meu"), 50, 50));
        animales.add(new Grupo.Araña("Shallan", "Araña", "Aracnidos", 100, 7, "T:\\TAI\\DEVELOPER\\DAW\\M3\\UF5\\Generics\\Tamagochi\\prueba poo\\src\\main\\p.png",information.getProperty("Meu"), 50, 50));
        animales.add(new Grupo.Caracol("Turbo", "Caracol", "Moluscos", 100, 8, "T:\\TAI\\DEVELOPER\\DAW\\M3\\UF5\\Generics\\Tamagochi\\prueba poo\\src\\main\\p.png",information.getProperty("Meu"), 50, 50));
        // Agrega más animales según sea necesario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_enciclopedia = new javax.swing.JButton();
        b_cuidar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b_enciclopedia.setBackground(java.awt.Color.black);
        b_enciclopedia.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        b_enciclopedia.setForeground(java.awt.Color.white);
        b_enciclopedia.setText("Enciclopedia");
        b_enciclopedia.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        b_enciclopedia.setFocusPainted(false);
        b_enciclopedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_enciclopediaActionPerformed(evt);
            }
        });

        b_cuidar.setBackground(java.awt.Color.black);
        b_cuidar.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        b_cuidar.setForeground(java.awt.Color.white);
        b_cuidar.setText("Cuidar");
        b_cuidar.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        b_cuidar.setFocusPainted(false);
        b_cuidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cuidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_enciclopedia, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(b_cuidar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(b_enciclopedia, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(b_cuidar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void misComponents() {
        mainPanel = new BackgroundPanel("/main/zoo.jpg"); // Usa la ruta relativa correcta para la imagen
        setContentPane(mainPanel);

        b_enciclopedia = new javax.swing.JButton();
        b_cuidar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // Configurar los botones
        b_enciclopedia.setText("Enciclopedia");
        b_enciclopedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_enciclopediaActionPerformed(evt);
            }
        });

        b_cuidar.setText("Cuidar");
        b_cuidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cuidarActionPerformed(evt);
            }
        });


        // Configurar el layout del panel principal
        mainPanel.setLayout(null); // Layout nulo para posicionar manualmente los componentes

        // Posicionar los botones
        b_enciclopedia.setBounds(90, 50, 220, 80);
        b_cuidar.setBounds(90, 150, 220, 80);

        // Añadir los botones al panel principal
        mainPanel.add(b_enciclopedia);
        mainPanel.add(b_cuidar);

        // Añadir el panel principal al JFrame
        setContentPane(mainPanel);
        mainPanel.revalidate();
        mainPanel.repaint();

    }


    private void b_enciclopediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_enciclopediaActionPerformed
        // TODO add your handling code here:
        new EnciclopediaDialog(animales, nivel).setVisible(true);


    }//GEN-LAST:event_b_enciclopediaActionPerformed

    private void b_cuidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cuidarActionPerformed
        // TODO add your handling code here:
         new Cuidar(animales, nivel).setVisible(true);
         
    }//GEN-LAST:event_b_cuidarActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cuidar;
    private javax.swing.JButton b_enciclopedia;
    // End of variables declaration//GEN-END:variables
}
